version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://db:27017/node-express-auth
      JWT_SECRET: supersecretkey
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - my-network

volumes:
  dbdata:

networks:
  my-network: